Develop
renproject/kv pull request #1
Opened 2019-05-08 06:41 UTC by tok-kkk

- Split the big store.go file into specific files.
- Migrate the IterableStore from `lightnode` to this package.
- Add more detailed comments with the interface 
- Add tests. (test coverage above 95%)

2019-05-22 04:21 UTC, loongy requested changes
Overall, this is a good first implementation of the KV storage library. However, I have pushed some changes that implement a more flexible architecture. The major changes:

- Databases are separated from stores. Databases only understand the storage of bytes, whereas stores also understand the encoding. For example: badgerdb, leveldb, and memdb are all databases, whereas json, and gob are both considered stores.
- Caching has been moved into its own package and is, itself, an implementation of a store. It wraps other stores and deletes key-value tuples that have not been accessed for at least the TTL duration.
- Support for gob encoding/decoding has been added.

Some things that now need doing:
- [ ] Support for LevelDB iterators.
- [ ] Fix test suites.

2019-05-22 04:21 UTC, loongy commented on badgerDB.go
> +package store
This file should be named `bdb.go` or `badgerdb.go` to stay consistent with standard capitalisation.

2019-05-22 04:21 UTC, loongy commented on levelDB.go
> +package store
This file should be named `ldb.go` or `leveldb.go` to stay consistent with standard capitalisation.

2019-05-22 04:21 UTC, loongy commented on cache.go
> +package store
This file should be named `mdb.go` or `memdb.go` to provide better semantic meaning for this implementation that is consistent with the other implementations.

2019-05-22 04:23 UTC, tok-kkk commented
Thanks. I'll go over the changes and finish things left. I'll let you know when it's ready for another review.

2019-05-23 05:46 UTC, loongy approved these changes

2019-05-23 05:46 UTC, merged